import "./globals.css";
import type { Metadata } from "next";
import { Stylish } from "next/font/google";
import Navbar from "../components/Navbar";
import Providers from "../components/Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const stylish = Stylish({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sh",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        style={{ height: "100dvh" }}
        className={`${stylish.variable} max-w-6xl flex flex-col mx-auto font-sh bg-white text-black dark:bg-[#090908] dark:text-white selection:bg-gray-50 dark:selection:bg-gray-800`}
      >
        <Providers>
          <Navbar />
          <main className="w-full h-full px-4 sm:px-6 lg:px-8 flex flex-1 flex-col">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
